# Generated by Django 5.1 on 2024-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='report_images/')),
            ],
        ),
    ]
